#!usr/bin/env bash
# This script installs 'Nginx HTTP' and redirects /redirect_me

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP;
echo "Hello World!" | sudo tee /var/www/html/index.html
# OR
# echo "Hello World!" > index.html

echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html;

        location /redirect_me {
            return 301 http://google.com;
        }
}" > default

sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart